system:
  maxprocs: 4
  metrics:
    enabled: true
    interval: 1 #second
    receiver:
      type: graphite
      params:
        namespace: metrics.flowd
        host: localhost
        port: 2003

components:
  udp_rcv_plain:
    module: receiver.udp
    params:
      bind_addr: :3101
  udp_rcv_pickle:
    module: receiver.udp
    params:
      bind_addr: :3102
  rcv_dmx:
    module: link.dmx
  graphite_msg_parser_plain:
    plugin: graphite
    constructor: NewMsgParser
    params:
      format: plain
  graphite_msg_parser_pickle:
    plugin: graphite
    constructor: NewMsgParser
    params:
      format: pickle
  replicator:
    module: link.replicator
    params:
      replicas: 1
      hash_key: metric-name
  tcp_7220:
    module: sink.tcp
    params:
      bind_addr: :7220
  tcp_7221:
    module: sink.tcp
    params:
      bind_addr: :7221
  tcp_7222:
    module: sink.tcp
    params:
      bind_addr: :7222
  tcp_7223:
    module: sink.tcp
    params:
      bind_addr: :7223
  tcp_7224:
    module: sink.tcp
    params:
      bind_addr: :7224
  tcp_7225:
    module: sink.tcp
    params:
      bind_addr: :7225
  tcp_7226:
    module: sink.tcp
    params:
      bind_addr: :7226
  tcp_7227:
    module: sink.tcp
    params:
      bind_addr: :7227
  tcp_7228:
    module: sink.tcp
    params:
      bind_addr: :7228
  tcp_7229:
    module: sink.tcp
    params:
      bind_addr: :7229
  tcp_7230:
    module: sink.tcp
    params:
      bind_addr: :7230
  tcp_7231:
    module: sink.tcp
    params:
      bind_addr: :7231

pipeline:
  udp_rcv_plain:
    connect: graphite_msg_parser_plain
  udp_rcv_pickle:
    connect: graphite_msg_parser_pickle
  rcv_dmx:
    links:
      - graphite_msg_parser_plain
      - graphite_msg_parser_pickle
    connect: replicator
  replicator:
    links:
      - tcp_7220
      - tcp_7221
      - tcp_7222
      - tcp_7223
      - tcp_7224
      - tcp_7225
      - tcp_7226
      - tcp_7227
      - tcp_7228
      - tcp_7229
      - tcp_7230
      - tcp_7231